# ===============================
# SERVER CONFIG
# ===============================
server.port=8081

# ===============================
# DATABASE CONFIG (MySQL)
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/gym_db
spring.datasource.username=root
spring.datasource.password=root

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# ===============================
# OPTIONAL (Good Practice)
# ===============================
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver